### ISSUE TITLE
Investigate Cross Platform Build Issues

### ISSUE THREAD

**Issue by ogarvey** [ogarvey/OGCd-iExplorer#2]
Log File provided by Whovian on Discord, from nixos (https://nixos.org/) [14c44095qx4vjrmq4mlwdb607zbyab2m-og-cd-i-explorer-0.0.2.drv.log](https://github.com/ogarvey/OGCd-iExplorer/files/15074246/14c44095qx4vjrmq4mlwdb607zbyab2m-og-cd-i-explorer-0.0.2.drv.log)

See also:

```
$  nix run .
Unhandled exception. System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libSkiaSharp' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable:
libfontconfig.so.1: cannot open shared object file: No such file or directory
/nix/store/dpp5bk2w7ci274dxid4fb5l6cj508s1s-dotnet-runtime-8.0.4/shared/Microsoft.NETCore.App/8.0.4/libSkiaSharp.so: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/libSkiaSharp.so: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/runtimes/linux-x64/native/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/nix/store/dpp5bk2w7ci274dxid4fb5l6cj508s1s-dotnet-runtime-8.0.4/shared/Microsoft.NETCore.App/8.0.4/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/liblibSkiaSharp.so: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/runtimes/linux-x64/native/libSkiaSharp: cannot open shared object file: No such file or directory
/nix/store/dpp5bk2w7ci274dxid4fb5l6cj508s1s-dotnet-runtime-8.0.4/shared/Microsoft.NETCore.App/8.0.4/libSkiaSharp: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/libSkiaSharp: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/runtimes/linux-x64/native/liblibSkiaSharp: cannot open shared object file: No such file or directory
/nix/store/dpp5bk2w7ci274dxid4fb5l6cj508s1s-dotnet-runtime-8.0.4/shared/Microsoft.NETCore.App/8.0.4/liblibSkiaSharp: cannot open shared object file: No such file or directory
/nix/store/5x8mc1qcj4crijliwxbnzykc9sc03r17-og-cd-i-explorer-0.0.2/lib/og-cd-i-explorer/liblibSkiaSharp: cannot open shared object file: No such file or directory

   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(Nullable`1 maxResourceBytes)
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options)
   at Avalonia.SkiaApplicationExtensions.<>c.<UseSkia>b__0_0()
   at Avalonia.AppBuilder.SetupUnsafe()
   at Avalonia.AppBuilder.Setup()
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at OGCdiExplorer.Program.Main(String[] args) in /build/source/OGCd-iExplorer/Program.cs:line 16
[1]    26165 IOT instruction  nix run .
```

**Comment by Whovian9369** [comment]
In case anyone wants to replicate this, here's the Nix files that I quickly threw together: [cdi_OGCd-iExplorer.zip](https://github.com/ogarvey/OGCd-iExplorer/files/15074368/cdi_OGCd-iExplorer.zip)
